apiVersion: v1
kind: ConfigMap
metadata:
  name: atlas-crud-aggregator-config
data:
  spring.security.oauth2.client.provider.atlas.token-uri: http://keycloak/auth/realms/master/protocol/openid-connect/token