apiVersion: v1
kind: Service
metadata:
  name: {{ include "crud-aggregator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "crud-aggregator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "crud-aggregator.selectorLabels" . | nindent 4 }}
