primary:
  extraEnvVars:
    - name: PGPASSWORD
      value: dbpassword
  extraVolumeMounts:
    - name: scripts
      mountPath: /docker-entrypoint-initdb.d/
  extraVolumes:
    - name: scripts
      configMap:
        name: scripts
global:
  postgresql:
    auth:
      postgresPassword: password
      username: dbuser
      password: dbpassword
      database: obsdb

commonAnnotations:
  kapp.k14s.io/change-group: "atlas/observation-crud-postgresql"
  kapp.k14s.io/change-rule: "upsert after upserting atlas/kafka-deployment"