auth:
  adminUser: admin
  adminPassword: admin

commonAnnotations:
  kapp.k14s.io/change-group: "keycloak"
  kapp.k14s.io/change-rule: "upsert after upserting keycloak-postgresql"

postgresql:
  commonAnnotations:
    kapp.k14s.io/change-group: "keycloak-postgresql"

service:
  type: ClusterIP

resources:
  limits:
    cpu: "5000m"
    memory: "3072Mi"
  requests:
    cpu: "1000m"
    memory: "1024Mi"