#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:library", "library")

#@ app = library.get("app")
#@ resource = app.export("resource")

#@overlay/match by=overlay.subset(resource("StatefulSet", "kafka-cp-kafka")),expects=1
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    kapp.k14s.io/change-group: atlas/kafka-broker
    kapp.k14s.io/change-rule: "upsert after upserting atlas/kafka-zookeeper"

#@overlay/match by=overlay.subset(resource("StatefulSet", "kafka-cp-zookeeper")),expects=1
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    kapp.k14s.io/change-group: atlas/kafka-zookeeper

#@overlay/match by=overlay.subset(resource("Deployment", "kafka-cp-control-center")),expects=1
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    kapp.k14s.io/change-group: atlas/kafka-control-center
    kapp.k14s.io/change-rule: "upsert after upserting atlas/kafka-broker"

#@overlay/match by=overlay.subset(resource("Deployment", "kafka-cp-schema-registry")),expects=1
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    kapp.k14s.io/change-group: atlas/kafka-schema-registry
    kapp.k14s.io/change-rule: "upsert after upserting atlas/kafka-broker"