#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:library", "library")

#@ app = library.get("app")
#@ resource = app.export("resource")

#@overlay/match by=overlay.subset(resource("Deployment", "kafka-cp-schema-registry")),expects=1
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    kapp.k14s.io/change-group: atlas/kafka-registry
    kapp.k14s.io/change-rule: "upsert after upserting atlas/kafka-broker"