#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:library", "library")

#@ app = library.get("app")
#@ resource = app.export("resource")

#@overlay/match by=overlay.subset(resource("StatefulSet", "kafka-cp-zookeeper")),expects=1
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    kapp.k14s.io/change-group: atlas/kafka-zookeeper