apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-sender
  labels:
    app: message-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-sender
  template:
    metadata:
      labels:
        app: message-sender
    spec:
      containers:
      - name: message-sender
        image: message-sender:0.0.1-SNAPSHOT
        env:
          - name: SPRING_CLOUD_STREAM_KAFKA_DEFAULT_PRODUCER_CONFIGURATION_SCHEMA_REGISTRY_URL
            value: "http://kafka-cp-schema-registry.kafka:8081"
          - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
            value: "kafka-cp-kafka.kafka:9092"
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: atlas-message-sender-service
spec:
  selector:
    app: message-sender
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9080